# Generated by Django 4.1.7 on 2023-03-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('socials', models.TextField(blank=True, help_text='Social media profiles, on separate lines', null=True)),
                ('bio', models.TextField(blank=True, max_length=921, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sportist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField(default=-1)),
                ('sport', models.CharField(max_length=48)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('still_playing', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=900, null=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('sportist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewing.sportist')),
            ],
        ),
    ]
