# Generated by Django 4.1.7 on 2023-03-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sportist',
        ),
    ]
