# Generated by Django 4.1.7 on 2023-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewing', '0002_delete_sportist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField(default=-1)),
                ('sport', models.CharField(max_length=48)),
                ('bio', models.TextField(blank=True, null=True)),
                ('still_playing', models.BooleanField()),
            ],
        ),
    ]
