# Generated by Django 4.1.7 on 2023-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportist',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sportist',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
