# Generated by Django 4.1.7 on 2023-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewing', '0004_sportist_image_alter_sportist_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('socials', models.TextField(blank=True, help_text='Social media profiles, on separate lines', null=True)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
