# Generated by Django 4.1.7 on 2023-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewing', '0006_contributor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='bio',
            field=models.TextField(blank=True, max_length=421, null=True),
        ),
    ]
