# Generated by Django 4.1.7 on 2023-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewing', '0010_remove_sportist_highlights_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
